[profile.default]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
ast = true
build_info = true
extra_output = ["storageLayout"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "openzeppelin-foundry-upgrades/=lib/openzeppelin-foundry-upgrades/src/",
    "script/=script/",
    "src/=src/",
    "test/=test/"
]

[fmt]
bracket_spacing = true

[doc]
out = "docs"
repository = "https://github.com/sscovil/upgradeable-smart-contracts"
